language: java
sudo: false
script:

jdk:
  - oraclejdk8  
  
addons:
sonarcloud:
organization: "team6project" 
token:
secure: 6dae3bef6e68bc98d11dc9ae00f85d19ce4cc29d 
script:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true -B -V 
- mvn test
- "mvn sonar:sonar -Dsonar.projectKey=team6project -Dsonar.organization=team6 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=6dae3bef6e68bc98d11dc9ae00f85d19ce4cc29d"
