language: java
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true test -B -V
jdk:
  - oraclejdk8


 addons:
  sonarcloud:
    organization: "team_6"
    token:
      secure: 9a27423c973a1d46d1a2e18007cc3e51abb107fb 
script:
  
  - "mvn cobertura:cobertura"
  - "mvn sonar:sonar -Dsonar.projectKey=team_6 -Dsonar.organization=team_6 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=9a27423c973a1d46d1a2e18007cc3e51abb107fb"
