language: java
sudo: false
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true test -B -V


  
jdk:
  - oraclejdk8
  
  
addons:
sonarcloud:
organization: "team6project" # the key of the org you chose at step #3
token:
secure: 6dae3bef6e68bc98d11dc9ae00f85d19ce4cc29d # encrypted value of your token
script:
# the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
- "mvn cobertura:cobertura"
- "mvn sonar:sonar -Dsonar.projectKey=team6project -Dsonar.organization=team6 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=6dae3bef6e68bc98d11dc9ae00f85d19ce4cc29d"
