language: java
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true test -B -V
jdk:
  - oraclejdk8


  addons:
  sonarcloud:
    organization: "team_6" # the key of the org you chose at step #3
    token:
      secure: 9a27423c973a1d46d1a2e18007cc3e51abb107fb # encrypted value of your token
script:
  # other script steps might be done before running the actual analysis
  - sonar-scanner
