language: java
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true test -B -V
mvn sonar:sonar \
  -Dsonar.projectKey=0.x \
  -Dsonar.organization=technionyp5779-team6 \
  -Dsonar.host.url=https://sonarcloud.io \
  -Dsonar.login=3efe1bd3837b45baf50e803fcdc1820218c3492d
jdk:
  - oraclejdk8
  
  